### Recuperar todas las peliculas
# Realiza una petición GET al endpoint raíz de movies.
# El servidor debería responder con un status 200 y el array completo de películas en formato JSON.
GET http://localhost:3000/movies

### Recuperar una pelicula por id
# Se utiliza un parámetro de ruta (path parameter). 
# El servidor usa 'req.params.id' para buscar la película específica en el JSON.
GET http://localhost:3000/movies/d8ae44f6-0b34-11f1-8ca4-00155df54daa
### Recuperar todas las peliculas por un genero
# Se utiliza una Query String (?genre=Action).
# El servidor extrae el valor con 'req.query.genre' y filtra el array usando '.filter()'.
GET http://localhost:3000/movies?genre=Action

### Crear una pelicula
# Envía una petición POST para crear un nuevo recurso.
# Es obligatorio indicar el 'Content-Type: application/json' para que el middleware 'express.json()' pueda procesarlo.
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Shrek",
  "rate": 9,
  "year": 2001,
  "director": "Andrew Adamson",
  "duration": 90,
  "poster": "https://i5.walmartimages.com/seo/Shrek-Movie-Poster-24x36-Entertainment-Decor-Art-Poster-24x36-Unframed-Age-Adults-Rectangle-Best-Posters_81e784d3-b362-4d6a-89f6-3713e4ad6ba8.2f462d58761f03f8df33196463cb1459.jpeg",
  "genre": ["Action", "Comedy", "Drama"]
}

### Editar una pelicula
# El método PATCH se usa para actualizaciones parciales.
# Aquí solo estamos enviando el campo "rate". Gracias a 'movieSchema.partial()' en Zod, 
# la validación no fallará aunque falten el resto de campos (título, año, etc.).
PATCH http://localhost:3000/movies/d8ae44f6-0b34-11f1-8ca4-00155df54daa
Content-Type: application/json

{
  "poster": "https://m.media-amazon.com/images/I/5151N2hUPiL._AC_.jpg"
}

### Eliminar una pelicula
# Se utiliza el método DELETE para eliminar un recurso específico.
DELETE http://localhost:3000/movies/d8ae44f6-0b34-11f1-8ca4-00155df54daa